import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Sidebar from "@/components/Sidebar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="h-lvh flex">
        <div className="w-1/3 shrink-0">
          <Sidebar />
        </div>
        <div className="h-lvh bg-white p-5">
          {children}
        </div>
      </body>
    </html>
  );
}
